apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://www-gcp.dev.nav.no/syk/sykepenger"
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  liveness:
    path: syk/sykepenger/api/isAlive
  readiness:
    path: syk/sykepenger/api/isReady
  accessPolicy:
    outbound:
      rules:
        - application: spinnsyn-backend
  tokenx:
    enabled: true
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.dev.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.dev.nav.no/login"
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "q1"
    - name: SYKEFRAVAER_URL
      value: "https://www-gcp.dev.nav.no/syk/sykefravaer"
    - name: DITTNAV_URL
      value: "https://www.dev.nav.no/person/dittnav/"
    - name: OPPLAERING
      value: "false"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepenger"
    - name: AMPLITUDE_KEY
      value: "7a887ba3e5a07c755526c6591810101a"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: DECORATOR_ENV
      value: "dev"
    - name: UTVIKLING_ARKIVERING
      value: "false"
    - name: ARKIVERING
      value: "false"
    - name: SPINNSYN_BACKEND_URL
      value: "http://spinnsyn-backend"
