apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend-interne
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://spinnsyn-frontend-interne.intern.nav.no/syk/sykepenger"
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 150Mi
  liveness:
    path: syk/sykepenger/api/isAlive
  readiness:
    path: syk/sykepenger/api/isReady
  accessPolicy:
    outbound:
      rules:
        - application: spinnsyn-backend
  env:
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "prod"
    - name: OPPLAERING
      value: "false"
    - name: AMPLITUDE_ENABLED
      value: "false"
    - name: DECORATOR_ENV
      value: "prod"
    - name: UTVIKLING_ARKIVERING
      value: "false"
    - name: ARKIVERING
      value: "false"
    - name: SPINNSYN_BACKEND_URL
      value: "http://spinnsyn-backend"
    - name: NO_DECORATOR
      value: "true"
    - name: SPINNSYN_FRONTEND_INTERNE
      value: "true"
    - name: SPINNSYN_BACKEND_CLIENT_ID
      value: "api://prod-gcp.flex.spinnsyn-backend/.default"
    - name: FLEX_FSS_PROXY_CLIENT_ID
      value: "api://prod-fss.flex.flex-fss-proxy/.default"
    - name: FLEX_FSS_PROXY_URL
      value: "https://flex-fss-proxy.prod-fss-pub.nais.io"
    - name: ASSET_PREFIX
      value: "https://flex-static-files.nav.no/spinnsyn"
