apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend-arkivering
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 4
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 300m
      memory: 128Mi
  liveness:
    path: syk/sykepenger/api/isAlive
  readiness:
    path: syk/sykepenger/api/isReady
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
      rules:
        - application: spinnsyn-backend
    inbound:
      rules:
        - application: spinnsyn-arkivering
  azure:
    application:
      enabled: true
  env:
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.nav.no/login"
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "prod"
    - name: SYKEFRAVAER_URL
      value: "https://www.nav.no/syk/sykefravaer"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
    - name: ARKIVERTE_VEDTAK_URL
      value: "https://person.nav.no/mine-saker/tema/SYK"
    - name: OPPLAERING
      value: "false"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www.nav.no/syk/sykepenger"
    - name: AMPLITUDE_ENABLED
      value: "false"
    - name: DECORATOR_ENV
      value: "prod"
    - name: NO_DECORATOR
      value: "true"
    - name: UTVIKLING_ARKIVERING
      value: "false"
    - name: ARKIVERING
      value: "true"
    - name: SPINNSYN_BACKEND_CLIENT_ID
      value: "api://prod-gcp.flex.spinnsyn-backend/.default"
    - name: SPINNSYN_BACKEND_URL
      value: "http://spinnsyn-backend"
