apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://sykepenger.labs.nais.io/"
  liveness:
    path: syk/sykepenger/api/isAlive
  readiness:
    path: syk/sykepenger/api/isReady
  env:
    - name: ENVIRONMENT
      value: "labs"
    - name: SYKEFRAVAER_URL
      value: "https://ditt-sykefravaer.labs.nais.io/syk/sykefravaer"
    - name: MINSIDE_URL
      value: "https://www.nav.no/minside/"
    - name: ARKIVERTE_VEDTAK_URL
      value: "https://person.nav.no/mine-saker/tema/SYK"
    - name: OPPLAERING
      value: "true"
    - name: LOGINSERVICE_URL
      value: "https://loginservice-q.nav.no/login"
    - name: MOCK_BACKEND
      value: "true"
    - name: AMPLITUDE_ENABLED
      value: "false"
    - name: DECORATOR_ENV
      value: "prod"
    - name: UTVIKLING_ARKIVERING
      value: "true"
    - name: ARKIVERING
      value: "false"
