apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend-arkivering
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 170Mi
  liveness:
    path: syk/sykepenger/api/isAlive
  readiness:
    path: syk/sykepenger/api/isReady
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
      rules:
        - application: spinnsyn-backend
    inbound:
      rules:
        - application: spinnsyn-arkivering
  azure:
    application:
      enabled: true
  env:
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.dev.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.dev.nav.no/login"
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "q1"
    - name: SYKEFRAVAER_URL
      value: "https://www-gcp.dev.nav.no/syk/sykefravaer"
    - name: MINSIDE_URL
      value: "https://www.dev.nav.no/minside/"
    - name: ARKIVERTE_VEDTAK_URL
      value: "https://person.dev.nav.no/mine-saker/tema/SYK"
    - name: OPPLAERING
      value: "false"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepenger"
    - name: AMPLITUDE_ENABLED
      value: "false"
    - name: DECORATOR_ENV
      value: "dev"
    - name: NO_DECORATOR
      value: "true"
    - name: UTVIKLING_ARKIVERING
      value: "false"
    - name: ARKIVERING
      value: "true"
    - name: SPINNSYN_BACKEND_CLIENT_ID
      value: "api://dev-gcp.flex.spinnsyn-backend/.default"
    - name: SPINNSYN_BACKEND_URL
      value: "http://spinnsyn-backend"
