apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://www.nav.no/syk/sykepenger"
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 200Mi
  liveness:
    path: syk/sykepenger/api/isAlive
  readiness:
    path: syk/sykepenger/api/isReady
  accessPolicy:
    outbound:
      rules:
        - application: spinnsyn-backend
  tokenx:
    enabled: true
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.nav.no/login"
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "prod"
    - name: SYKEFRAVAER_URL
      value: "https://www.nav.no/syk/sykefravaer"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
    - name: ARKIVERTE_VEDTAK_URL
      value: "https://person.nav.no/mine-saker/tema/SYK"
    - name: OPPLAERING
      value: "false"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www.nav.no/syk/sykepenger"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: DECORATOR_ENV
      value: "prod"
    - name: UTVIKLING_ARKIVERING
      value: "false"
    - name: ARKIVERING
      value: "false"
    - name: SPINNSYN_BACKEND_URL
      value: "http://spinnsyn-backend"
    - name: SPINNSYN_BACKEND_TOKENX_CLIENT_ID
      value: "prod-gcp:flex:spinnsyn-backend"
    - name: ASSET_PREFIX
      value: "https://flex-static-files.nav.no/spinnsyn"
