apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appname}}
  namespace: flex
  labels:
    team: flex
    branchState: {{ branchState }}
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ ingress }}
  replicas:
    min: {{ replicas }}
    max: {{ replicas }}
  liveness:
    path: syk/sykepenger/api/internal/isAlive
  readiness:
    path: syk/sykepenger/api/internal/isReady
  accessPolicy:
    rules:
      - application: nav-dekoratoren
        namespace: personbruker
  env:
    - name: ENVIRONMENT
      value: "labs"
    - name: SYKEFRAVAER_URL
      value: "https://demo.ekstern.dev.nav.no/syk/sykefravaer"
    - name: MINSIDE_URL
      value: "https://www.nav.no/minside/"
    - name: ARKIVERTE_VEDTAK_URL
      value: "https://person.nav.no/mine-saker/tema/SYK"
    - name: OPPLAERING
      value: "true"
    - name: MOCK_BACKEND
      value: "true"
    - name: AMPLITUDE_ENABLED
      value: "false"
    - name: DECORATOR_ENV
      value: "prod"
    - name: UTVIKLING_ARKIVERING
      value: "true"
    - name: ARKIVERING
      value: "false"
    - name: ASSET_PREFIX
      value: "https://cdn.nav.no/flex/spinnsyn-frontend"
