ingress: https://www-gcp.dev.nav.no/syk/sykepenger
env:
  FLEX_GATEWAY_ROOT: "https://flex-gateway.dev.nav.no"
  MOCK_BACKEND: "false"
  ENVIRONMENT: "q1"
  SYKEFRAVAER_URL: "https://www-gcp.dev.nav.no/syk/sykefravaer"
  MINSIDE_URL: "https://www.dev.nav.no/minside/"
  ARKIVERTE_VEDTAK_URL: "https://person.dev.nav.no/mine-saker/tema/SYK"
  OPPLAERING: "false"
  AMPLITUDE_ENABLED: "true"
  DECORATOR_ENV: "dev"
  UTVIKLING_ARKIVERING: "false"
  ARKIVERING: "false"
  SPINNSYN_BACKEND_URL: "http://spinnsyn-backend"
  SPINNSYN_BACKEND_TOKENX_CLIENT_ID: "dev-gcp:flex:spinnsyn-backend"
  ASSET_PREFIX: https://cdn.nav.no/flex/spinnsyn-frontend
  SOKOS_KONTOREGISTER_PERSON_TOKENX_CLIENT_ID: "dev-gcp:okonomi:sokos-kontoregister-person"
