apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  replicas:
    min: 2
    max: 4
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  preStopHook:
    http:
      path: syk/sykepenger/api/internal/preStop
      port: 8080
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  liveness:
    path: syk/sykepenger/api/internal/isAlive
  readiness:
    path: syk/sykepenger/api/internal/isReady
  startup:
    path: syk/sykepenger/api/internal/isAlive
    initialDelay: 30
  frontend:
    generatedConfig:
      mountPath: /usr/share/nginx/html/js/nais.js
  accessPolicy:
    outbound:
      rules:
        - application: spinnsyn-backend
        - application: flexjar-backend
        - application: flex-hotjar-emotions
        - application: sokos-kontoregister-person
          namespace: okonomi
        - application: nav-dekoratoren
          namespace: personbruker
      external:
  {{#each external-host}}
        - host: {{this}}
  {{/each}}
  tokenx:
    enabled: true
  envFrom:
    - secret: spinnsyn-frontend-unleash-api-token
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
