ingress: https://www.nav.no/syk/sykepenger
cpu: 200m
memory: 384Mi
external-host:
  - flex-unleash-api.nav.cloud.nais.io
env:
  FLEX_GATEWAY_ROOT: "https://flex-gateway.nav.no"
  SPINNSYN_BACKEND_URL: "http://spinnsyn-backend"
  SPINNSYN_BACKEND_TOKENX_CLIENT_ID: "prod-gcp:flex:spinnsyn-backend"
  SOKOS_KONTOREGISTER_PERSON_TOKENX_CLIENT_ID: "prod-gcp:okonomi:sokos-kontoregister-person"
  FLEXJAR_BACKEND_TOKENX_CLIENT_ID: "prod-gcp:flex:flexjar-backend"
