ingress: https://www.nav.no/syk/sykepenger
env:
  FLEX_GATEWAY_ROOT: "https://flex-gateway.nav.no"
  LOGINSERVICE_URL: "https://loginservice.nav.no/login"
  MOCK_BACKEND: "false"
  ENVIRONMENT: "prod"
  SYKEFRAVAER_URL: "https://www.nav.no/syk/sykefravaer"
  MINSIDE_URL: "https://www.nav.no/minside/"
  ARKIVERTE_VEDTAK_URL: "https://person.nav.no/mine-saker/tema/SYK"
  OPPLAERING: "false"
  LOGINSERVICE_REDIRECT_URL: "https://www.nav.no/syk/sykepenger"
  AMPLITUDE_ENABLED: "true"
  DECORATOR_ENV: "prod"
  UTVIKLING_ARKIVERING: "false"
  ARKIVERING: "false"
  SPINNSYN_BACKEND_URL: "http://spinnsyn-backend"
  SPINNSYN_BACKEND_TOKENX_CLIENT_ID: "prod-gcp:flex:spinnsyn-backend"
  ASSET_PREFIX: "https://flex-static-files.nav.no/spinnsyn"
  SOKOS_KONTOREGISTER_PERSON_TOKENX_CLIENT_ID: "prod-gcp:okonomi:sokos-kontoregister-person"
