env:
  FLEX_GATEWAY_ROOT: https://flex-gateway.dev.nav.no
  LOGINSERVICE_URL: https://loginservice.dev.nav.no/login
  MOCK_BACKEND: false
  ENVIRONMENT: q1
  SYKEFRAVAER_URL: https://www-gcp.dev.nav.no/syk/sykefravaer
  MINSIDE_URL: https://www.dev.nav.no/minside/
  ARKIVERTE_VEDTAK_URL: https://person.dev.nav.no/mine-saker/tema/SYK
  OPPLAERING: false
  LOGINSERVICE_REDIRECT_URL: https://www-gcp.dev.nav.no/syk/sykepenger
  AMPLITUDE_ENABLED: false
  DECORATOR_ENV: dev
  NO_DECORATOR: true
  UTVIKLING_ARKIVERING: false
  ARKIVERING: true
  SPINNSYN_BACKEND_CLIENT_ID: api://dev-gcp.flex.spinnsyn-backend/.default
  SPINNSYN_BACKEND_URL: http://spinnsyn-backend
