apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend-arkivering
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: {{min}}
    max: {{max}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  preStopHook:
    http:
      path: syk/sykepenger/api/internal/preStop
      port: 3000
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  liveness:
    path: syk/sykepenger/api/internal/isAlive
  readiness:
    path: syk/sykepenger/api/internal/isReady
  startup:
    path: syk/sykepenger/api/internal/isAlive
    initialDelay: 30
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
      rules:
        - application: spinnsyn-backend
    inbound:
      rules:
        - application: spinnsyn-arkivering
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  azure:
    application:
      enabled: true
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}

