env:
  FLEX_GATEWAY_ROOT: https://flex-gateway.nav.no
  LOGINSERVICE_URL: https://loginservice.nav.no/login
  MOCK_BACKEND: false
  ENVIRONMENT: prod
  SYKEFRAVAER_URL: https://www.nav.no/syk/sykefravaer
  MINSIDE_URL: https://www.nav.no/minside/
  ARKIVERTE_VEDTAK_URL: https://person.nav.no/mine-saker/tema/SYK
  OPPLAERING: false
  LOGINSERVICE_REDIRECT_URL: https://www.nav.no/syk/sykepenger
  AMPLITUDE_ENABLED: false
  DECORATOR_ENV: prod
  NO_DECORATOR: true
  UTVIKLING_ARKIVERING: false
  ARKIVERING: true
  SPINNSYN_BACKEND_CLIENT_ID: api://prod-gcp.flex.spinnsyn-backend/.default
  SPINNSYN_BACKEND_URL: http://spinnsyn-backend
