const UtbetalingTekster = {
    'utbetaling.systemtittel': 'Utbetales til arbeidsgiveren',
    'utbetaling.trekk': '* Når du får utbetalt sykepengene fra arbeidsgiveren din, har arbeidsgiveren trukket skatt og eventuelt andre faste trekk fra dette beløpet.',
    'utbetaling.mndlonn.tittel': 'Månedslønnen',
    'utbetaling.mndlonn.innhold': 'Først beregner arbeidsgiveren din gjennomsnittet av inntekten din de siste tre kalendermånedene før du ble syk.',
    'utbetaling.arslonn.tittel': 'Årslønn',
    'utbetaling.arslonn.innhold': 'Så blir månedslønnen omregnet til årslønn ved å gange den med 12.',
    'utbetaling.dagligbelop.tittel': 'Daglig beløp',
    'utbetaling.dagligbelop.innhold': 'Deretter deler vi årslønnen på 260, da får vi dagsatsen. Årslønnen blir redusert til 6 ganger folketrygdens grunnbeløp hvis du tjener mer enn det.',
    'utbetaling.utbetalingsdager.tittel': 'Utbetalingsdager',
    'utbetaling.utbetalingsdager.innhold': 'Når NAV utbetaler sykepenger, betales det alltid for dagene mandag til fredag. Dette gjør vi selv om det er helligdager i løpet av disse dagene, og uavhengig av om du eventuelt jobber lørdag og søndag.',
    'utbetaling.totalbelop.tittel': 'Totalbeløp',
    'utbetaling.totalbelop.innhold': 'Til slutt ganger vi daglig beløp med antallet utbetalingsdager.',
    'utbetaling.totalbelop.innhold-2': 'Utbetalingen blir redusert til 6 ganger folketrygdens grunnbeløp hvis du tjener mer enn det til sammen. Har du flere arbeidsforhold, blir reduksjonen fordelt slik at det tilsvarer forholdet mellom inntektene.',
    'utbetaling.delvis.tittel': 'Hvis du er delvis sykmeldt',
    'utbetaling.delvis.innhold': 'Er du sykmeldt i mindre enn 100 %, vil dagsatsen bli ganget med den prosenten du er sykmeldt. Endrer prosenten seg underveis, beregner vi de ulike dagene med riktig prosent.',
    'utbetaling.beregning.tittel': 'Mer om beregningen',
    'utbetaling.beregning.les.mer': 'Du kan lese mer om hvordan sykepengene beregnes i ',
    'utbetaling.beregning.lenke.tekst': 'folketrygdloven § 8-28 til 30.',
    'utbetaling.beregning.lenke.url': 'https://lovdata.no/lov/1997-02-28-19/§8-28',
    'utbetaling.opplysninger.tittel': 'Ved feil opplysninger',
    'utbetaling.opplysninger.inntektsmelding': 'Når vi beregner sykepengene dine, bruker vi månedsinntekten som arbeidsgiveren din oppgir i inntektsmeldingen. Er du usikker på om månedsinntekten er riktig, kontakt arbeidsgiveren din.',
    'utbetaling.inntekt.info.tittel': 'Slik beregner vi sykepengene',
    'utbetaling.inntekt.info.beregnet': 'Beregnet månedslønn',
    'utbetaling.inntekt.info.omregnet': 'Omregnet til årslønn',
    'utbetaling.inntekt.info.daglig': 'Daglig utbetalingsbeløp',
    'utbetaling.inntekt.info.utbetalingsdager': 'Utbetalingsdager',
    'utbetaling.inntekt.info.sykepengebelop': 'Sykepengebeløp *',
    'utbetaling.refusjon.periode': 'Periode',
    'utbetaling.refusjon.refunderes': 'Refunderes til',
    'utbetaling.refusjon.orgnr': 'Organisasjonsnummer',
    'utbetaling.arbeidsgiver.tittel': 'Beløpet går til arbeidsgiveren din',
    'utbetaling.arbeidsgiver.tekst': 'Vi har registrert at du får sykepenger fra %ARBEIDSGIVER%, som skal ha pengene tilbake fra NAV. Selv om pengene går til arbeidsgiveren din, er vi forpliktet til å vise deg informasjonen fordi det handler om deg.',

    'utbetaling.tabell.dagtyper': 'Mer om dagtyper',
    'utbetaling.tabell.label.ArbeidsgiverperiodeDag': 'Arbeidsgiveren din betaler de første 16 kalenderdagene av sykefraværet.',
    'utbetaling.tabell.label.Arbeidsdag': 'Det utbetales ikke sykepenger for hele dager du har vært på jobben.',
    'utbetaling.tabell.label.NavDagSyk': 'Du har vært syk en hel dag, og du får sykepenger for denne dagen.',
    'utbetaling.tabell.label.NavDagDelvisSyk': 'Du får sykepenger for den delen av arbeidstiden du ikke jobber. Vi bruker opplysningene dine om hvor mye du jobbet i perioden.',
    'utbetaling.tabell.label.NavHelgDag': 'Sykepenger betales alltid fra mandag til fredag. Om du jobber lørdager og søndager blir dette medregnet i totalbeløpet.',
    'utbetaling.tabell.label.Fridag': 'Du får ikke sykepenger for dager du har ferie eller permisjon.',
    'utbetaling.tabell.label.ForeldetDag': 'Søknaden må sendes senest tre måneder etter den siste dagen i sykmeldingsperioden.',
    'utbetaling.tabell.label.UkjentDag': 'Vi har ikke mottatt informasjon om denne dagen, så den regnes som arbeidsdag.',

    'utbetaling.tabell.avvist.SykepengedagerOppbrukt': 'Du har vært sykmeldt i mer enn 260 dager, som er det maksimale antallet dager du kan få sykepenger hvis du er under 67 år. Fra du er blitt 67 år har du rett til 60 dager. Det må gå 26 uker uten sykepenger eller arbeidsavklaringspenger før du kan få sykepenger igjen.',
    'utbetaling.tabell.avvist.MinimumInntekt': 'Du må ha en årlig inntekt på minst et halvt ' +
        '<a href="https://www.nav.no/no/nav-og-samfunn/kontakt-nav/utbetalinger/grunnbelopet-i-folketrygden" target="_blank">grunnbeløp</a> ' +
        ' for å få sykepenger.',
    'utbetaling.tabell.avvist.EgenmeldingUtenforArbeidsgiverperiode': 'Egenmelding kan bare brukes i arbeidsgiverperioden, det vil si de første 16 dagene av sykefraværet som arbeidsgiveren betaler. Etter dette må du ha sykmelding og sende inn søknad for at NAV skal betale.',
    'utbetaling.tabell.avvist.MinimumSykdomsgrad': 'Du må være minst 20 prosent sykmeldt for å få sykepenger.',
    'utbetaling.tabell.avvist.ManglerOpptjening': 'Du må ha vært i arbeid i minst fire uker rett før sykefraværet.',
    'utbetaling.tabell.avvist.ManglerMedlemskap': 'Du må være medlem i folketrygden for å få sykepenger. Du er medlem bare hvis du bor eller jobber i Norge.',
    'utbetaling.tabell.avvist.EtterDødsdato': 'Det blir ikke utbetalt sykepenger etter datoen for dødsfallet.',
    'utbetaling.tabell.avvist.UKJENT': 'Beskrivelse kommer...',
}

export default UtbetalingTekster
