ingress: https://spinnsyn-frontend-interne.dev.intern.nav.no/syk/sykepenger
env:
  MOCK_BACKEND: false
  ENVIRONMENT: q1
  OPPLAERING: false
  AMPLITUDE_ENABLED: false
  DECORATOR_ENV: dev
  UTVIKLING_ARKIVERING: false
  ARKIVERING: false
  SPINNSYN_BACKEND_URL: http://spinnsyn-backend
  NO_DECORATOR: true
  SPINNSYN_FRONTEND_INTERNE: true
  SPINNSYN_BACKEND_CLIENT_ID: api://dev-gcp.flex.spinnsyn-backend/.default
  FLEX_FSS_PROXY_CLIENT_ID: api://dev-fss.flex.flex-fss-proxy/.default
  FLEX_FSS_PROXY_URL: https://flex-fss-proxy.dev-fss-pub.nais.io
  ASSET_PREFIX: https://flex-static-files.dev.nav.no/spinnsyn
