ingress: https://spinnsyn-frontend-interne.intern.dev.nav.no/syk/sykepenger
cpu: 50m
memory: 256Mi
external-host:
  - modiacontextholder-q1.dev-fss-pub.nais.io
env:
  NO_DECORATOR: "true"
  SPINNSYN_BACKEND_URL: http://spinnsyn-backend
  SPINNSYN_BACKEND_CLIENT_ID: api://dev-gcp.flex.spinnsyn-backend/.default
  MODIACONTEXTHOLDER_SCOPE: api://dev-gcp.personoversikt.modiacontextholder/.default
  MODIACONTEXTHOLDER_URL: http://modiacontextholder.personoversikt
