ingress: https://spinnsyn-frontend-interne.dev.intern.nav.no/syk/sykepenger
env:
  MOCK_BACKEND: false
  ENVIRONMENT: q1
  OPPLAERING: false
  AMPLITUDE_ENABLED: false
  DECORATOR_ENV: dev
  UTVIKLING_ARKIVERING: false
  ARKIVERING: false
  SPINNSYN_BACKEND_URL: http://spinnsyn-backend
  NO_DECORATOR: true
  SPINNSYN_FRONTEND_INTERNE: true
  SPINNSYN_BACKEND_CLIENT_ID: api://dev-gcp.flex.spinnsyn-backend/.default
  ASSET_PREFIX: https://cdn.nav.no/flex/spinnsyn-frontend
  MODIACONTEXTHOLDER_SCOPE: api://dev-fss.personoversikt.modiacontextholder-q0/.default
  MODIACONTEXTHOLDER_URL: https://modiacontextholder-q0.dev-fss-pub.nais.io
