apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend-interne
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ ingress }}
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 90
  resources:
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 150Mi
  liveness:
    path: syk/sykepenger/api/internal/isAlive
  readiness:
    path: syk/sykepenger/api/internal/isReady
  startup:
    path: syk/sykepenger/api/internal/isAlive
    initialDelay: 30
  accessPolicy:
    outbound:
      rules:
        - application: spinnsyn-backend
      external:
  {{ #each external-host}}
        - host: {{this } }
  {{/each}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
