ingress: https://spinnsyn-frontend-interne.intern.nav.no/syk/sykepenger
cpu: 100m
memory: 200Mi
external-host:
  - modiacontextholder.prod-fss-pub.nais.io
env:
  MOCK_BACKEND: false
  ENVIRONMENT: prod
  OPPLAERING: false
  AMPLITUDE_ENABLED: false
  DECORATOR_ENV: prod
  UTVIKLING_ARKIVERING: false
  ARKIVERING: false
  SPINNSYN_BACKEND_URL: http://spinnsyn-backend
  NO_DECORATOR: true
  SPINNSYN_FRONTEND_INTERNE: true
  SPINNSYN_BACKEND_CLIENT_ID: api://prod-gcp.flex.spinnsyn-backend/.default
  ASSET_PREFIX: https://cdn.nav.no/flex/spinnsyn-frontend
  MODIACONTEXTHOLDER_SCOPE: api://prod-fss.personoversikt.modiacontextholder/.default
  MODIACONTEXTHOLDER_URL: https://modiacontextholder.prod-fss-pub.nais.io
